"""empty message

Revision ID: b691c95ecb21
Revises: eb540709890a
Create Date: 2019-10-13 12:06:54.897257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b691c95ecb21'
down_revision = 'eb540709890a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password2_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password2_hash')
    # ### end Alembic commands ###
